/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../../public/macintosh.glb --transform --types -K 
Files: ../../../public/macintosh.glb [9.89MB] > macintosh-transformed.glb [45.46KB] (100%)
Author: Daniel O'Neil (https://sketchfab.com/doneil)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-classic-1991-3b66e98d137d4a23aaa725ce0a8aec28
Title: Macintosh Classic (1991)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mac_Tri_Baked_MacTriBaked_0: THREE.Mesh
  }
  materials: {
    ['Mac.Tri.Baked']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/macintosh-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Mac_Tri_Baked_MacTriBaked_0.geometry} material={materials['Mac.Tri.Baked']} position={[-0.222, 0, 0]} scale={0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/macintosh-transformed.glb')
